image: Ubuntu1804  # образ для сборки

stack: node 16  # окружение

branches:
  only:
    - master  # ветка git

cache: node_modules  # кеширование

install:
  - yarn  # команда установки зависимостей
  - yarn add push-dir

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - yarn build   # команда сборки

test_script:
  - yarn lint # скрипт тестирования

deploy_script:  # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://$HW:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - yarn push-dir --dir=dist --branch=gh-pages --force --verbose